# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for ynab-export

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # You may remove this if you don't need to generate anything before building.
    - go mod download

builds:
  - id: ynab-export
    main: .
    binary: ynab-export

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Build flags
    flags:
      - -trimpath

    # Linker flags for smaller binaries
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

    # Environment variables for build
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=jsonv2

    # Build tags for pure Go Gio builds
    tags:
      - nowayland
      - nox11
      - nogl

# Disable archives - we want raw binaries in the release
archives:
  - formats: binary

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: StephenBrown2
    name: ynab-export

  # Draft release (change to false for automatic release)
  draft: false

  # Mark as prerelease
  prerelease: auto

  # Release name template
  name_template: "{{.ProjectName}} v{{.Version}}"

  # Header and footer for release notes
  header: |
    ## YNAB Budget Exporter v{{ .Version }}

    A simple tool to export your YNAB budget for import into Actual Budget.

  footer: |
    ---

    **Full Changelog**: https://github.com/StephenBrown2/ynab-export/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    Download the appropriate binary for your platform from the assets below.

    ### Usage

    1. Download the binary for your operating system
    2. Run the executable (no installation required)
    3. Follow the on-screen prompts

    For more information, see the [README](https://github.com/StephenBrown2/ynab-export/blob/main/README.md).
