# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for ynab-export

builds:
  - id: ynab-export
    # Use prebuilt binaries from fyne-cross
    builder: prebuilt

    # Must specify all targets when using prebuilt
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

    # Skip invalid combinations
    ignore:
      - goos: windows
        goarch: arm64

    # Prebuilt configuration
    prebuilt:
      # Path template to the prebuilt binaries (fyne-cross output)
      path: dist/ynab-export_{{ .Os }}_{{ .Arch }}{{ .Ext }}

    # Binary name in the release
    binary: ynab-export

# Create archives with the prebuilt binaries
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: StephenBrown2
    name: ynab-export

  # Draft release (change to false for automatic release)
  draft: false

  # Mark as prerelease
  prerelease: auto

  # Release name template
  name_template: "{{.ProjectName}} v{{.Version}}"

  # Header and footer for release notes
  header: |
    ## YNAB Budget Exporter v{{ .Version }}

    A simple tool to export your YNAB budget for import into Actual Budget.

  footer: |
    ---

    **Full Changelog**: https://github.com/StephenBrown2/ynab-export/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    Download the appropriate binary for your platform from the assets below.

    ### Usage

    1. Download the binary for your operating system
    2. Run the executable (no installation required)
    3. Follow the on-screen prompts

    For more information, see the [README](https://github.com/StephenBrown2/ynab-export/blob/main/README.md).
