//go:build go1.22

// Package mockserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package mockserver

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for AccountType.
const (
	AutoLoan       AccountType = "autoLoan"
	Cash           AccountType = "cash"
	Checking       AccountType = "checking"
	CreditCard     AccountType = "creditCard"
	LineOfCredit   AccountType = "lineOfCredit"
	MedicalDebt    AccountType = "medicalDebt"
	Mortgage       AccountType = "mortgage"
	OtherAsset     AccountType = "otherAsset"
	OtherDebt      AccountType = "otherDebt"
	OtherLiability AccountType = "otherLiability"
	PersonalLoan   AccountType = "personalLoan"
	Savings        AccountType = "savings"
	StudentLoan    AccountType = "studentLoan"
)

// Defines values for CategoryGoalType.
const (
	CategoryGoalTypeDEBT        CategoryGoalType = "DEBT"
	CategoryGoalTypeLessThannil CategoryGoalType = "<nil>"
	CategoryGoalTypeMF          CategoryGoalType = "MF"
	CategoryGoalTypeNEED        CategoryGoalType = "NEED"
	CategoryGoalTypeTB          CategoryGoalType = "TB"
	CategoryGoalTypeTBD         CategoryGoalType = "TBD"
)

// Defines values for ScheduledTransactionSummaryFrequency.
const (
	Daily           ScheduledTransactionSummaryFrequency = "daily"
	Every3Months    ScheduledTransactionSummaryFrequency = "every3Months"
	Every4Months    ScheduledTransactionSummaryFrequency = "every4Months"
	Every4Weeks     ScheduledTransactionSummaryFrequency = "every4Weeks"
	EveryOtherMonth ScheduledTransactionSummaryFrequency = "everyOtherMonth"
	EveryOtherWeek  ScheduledTransactionSummaryFrequency = "everyOtherWeek"
	EveryOtherYear  ScheduledTransactionSummaryFrequency = "everyOtherYear"
	Monthly         ScheduledTransactionSummaryFrequency = "monthly"
	Never           ScheduledTransactionSummaryFrequency = "never"
	TwiceAMonth     ScheduledTransactionSummaryFrequency = "twiceAMonth"
	TwiceAYear      ScheduledTransactionSummaryFrequency = "twiceAYear"
	Weekly          ScheduledTransactionSummaryFrequency = "weekly"
	Yearly          ScheduledTransactionSummaryFrequency = "yearly"
)

// Defines values for TransactionClearedStatus.
const (
	Cleared    TransactionClearedStatus = "cleared"
	Reconciled TransactionClearedStatus = "reconciled"
	Uncleared  TransactionClearedStatus = "uncleared"
)

// Defines values for TransactionFlagColor.
const (
	TransactionFlagColorBlue        TransactionFlagColor = "blue"
	TransactionFlagColorEmpty       TransactionFlagColor = ""
	TransactionFlagColorGreen       TransactionFlagColor = "green"
	TransactionFlagColorLessThannil TransactionFlagColor = "<nil>"
	TransactionFlagColorOrange      TransactionFlagColor = "orange"
	TransactionFlagColorPurple      TransactionFlagColor = "purple"
	TransactionFlagColorRed         TransactionFlagColor = "red"
	TransactionFlagColorYellow      TransactionFlagColor = "yellow"
)

// Defines values for TransactionSummaryDebtTransactionType.
const (
	BalanceAdjustment TransactionSummaryDebtTransactionType = "balanceAdjustment"
	Charge            TransactionSummaryDebtTransactionType = "charge"
	Credit            TransactionSummaryDebtTransactionType = "credit"
	Escrow            TransactionSummaryDebtTransactionType = "escrow"
	Fee               TransactionSummaryDebtTransactionType = "fee"
	Interest          TransactionSummaryDebtTransactionType = "interest"
	LessThannil       TransactionSummaryDebtTransactionType = "<nil>"
	Payment           TransactionSummaryDebtTransactionType = "payment"
	Refund            TransactionSummaryDebtTransactionType = "refund"
)

// Account defines model for Account.
type Account struct {
	// Balance The current balance of the account in milliunits format
	Balance int64 `json:"balance"`

	// ClearedBalance The current cleared balance of the account in milliunits format
	ClearedBalance int64 `json:"cleared_balance"`

	// Closed Whether this account is closed or not
	Closed              bool                      `json:"closed"`
	DebtEscrowAmounts   *LoanAccountPeriodicValue `json:"debt_escrow_amounts"`
	DebtInterestRates   *LoanAccountPeriodicValue `json:"debt_interest_rates"`
	DebtMinimumPayments *LoanAccountPeriodicValue `json:"debt_minimum_payments"`

	// DebtOriginalBalance This field is deprecated and will always be null.
	DebtOriginalBalance *int64 `json:"debt_original_balance"`

	// Deleted Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// DirectImportInError If an account linked to a financial institution (direct_import_linked=true) and the linked connection is not in a healthy state, this will be true.
	DirectImportInError *bool `json:"direct_import_in_error,omitempty"`

	// DirectImportLinked Whether or not the account is linked to a financial institution for automatic transaction import.
	DirectImportLinked *bool              `json:"direct_import_linked,omitempty"`
	Id                 openapi_types.UUID `json:"id"`

	// LastReconciledAt A date/time specifying when the account was last reconciled.
	LastReconciledAt *time.Time `json:"last_reconciled_at"`
	Name             string     `json:"name"`
	Note             *string    `json:"note"`

	// OnBudget Whether this account is on budget or not
	OnBudget bool `json:"on_budget"`

	// TransferPayeeId The payee id which should be used when transferring to this account
	TransferPayeeId *openapi_types.UUID `json:"transfer_payee_id"`

	// Type The type of account
	Type AccountType `json:"type"`

	// UnclearedBalance The current uncleared balance of the account in milliunits format
	UnclearedBalance int64 `json:"uncleared_balance"`
}

// AccountType The type of account
type AccountType string

// BudgetDetail defines model for BudgetDetail.
type BudgetDetail struct {
	Accounts       *[]Account       `json:"accounts,omitempty"`
	Categories     *[]Category      `json:"categories,omitempty"`
	CategoryGroups *[]CategoryGroup `json:"category_groups,omitempty"`

	// CurrencyFormat The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
	CurrencyFormat *CurrencyFormat `json:"currency_format"`

	// DateFormat The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
	DateFormat *DateFormat `json:"date_format"`

	// FirstMonth The earliest budget month
	FirstMonth *openapi_types.Date `json:"first_month,omitempty"`
	Id         openapi_types.UUID  `json:"id"`

	// LastModifiedOn The last time any changes were made to the budget from either a web or mobile client
	LastModifiedOn *time.Time `json:"last_modified_on,omitempty"`

	// LastMonth The latest budget month
	LastMonth                *openapi_types.Date            `json:"last_month,omitempty"`
	Months                   *[]MonthDetail                 `json:"months,omitempty"`
	Name                     string                         `json:"name"`
	PayeeLocations           *[]PayeeLocation               `json:"payee_locations,omitempty"`
	Payees                   *[]Payee                       `json:"payees,omitempty"`
	ScheduledSubtransactions *[]ScheduledSubTransaction     `json:"scheduled_subtransactions,omitempty"`
	ScheduledTransactions    *[]ScheduledTransactionSummary `json:"scheduled_transactions,omitempty"`
	Subtransactions          *[]SubTransaction              `json:"subtransactions,omitempty"`
	Transactions             *[]TransactionSummary          `json:"transactions,omitempty"`
}

// BudgetDetailResponse defines model for BudgetDetailResponse.
type BudgetDetailResponse struct {
	Data struct {
		Budget BudgetDetail `json:"budget"`

		// ServerKnowledge The knowledge of the server
		ServerKnowledge int64 `json:"server_knowledge"`
	} `json:"data"`
}

// BudgetSummary defines model for BudgetSummary.
type BudgetSummary struct {
	// Accounts The budget accounts (only included if `include_accounts=true` specified as query parameter)
	Accounts *[]Account `json:"accounts,omitempty"`

	// CurrencyFormat The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
	CurrencyFormat *CurrencyFormat `json:"currency_format"`

	// DateFormat The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
	DateFormat *DateFormat `json:"date_format"`

	// FirstMonth The earliest budget month
	FirstMonth *openapi_types.Date `json:"first_month,omitempty"`
	Id         openapi_types.UUID  `json:"id"`

	// LastModifiedOn The last time any changes were made to the budget from either a web or mobile client
	LastModifiedOn *time.Time `json:"last_modified_on,omitempty"`

	// LastMonth The latest budget month
	LastMonth *openapi_types.Date `json:"last_month,omitempty"`
	Name      string              `json:"name"`
}

// BudgetSummaryResponse defines model for BudgetSummaryResponse.
type BudgetSummaryResponse struct {
	Data struct {
		Budgets       []BudgetSummary `json:"budgets"`
		DefaultBudget *BudgetSummary  `json:"default_budget"`
	} `json:"data"`
}

// Category defines model for Category.
type Category struct {
	// Activity Activity amount in milliunits format
	Activity int64 `json:"activity"`

	// Balance Balance in milliunits format
	Balance int64 `json:"balance"`

	// Budgeted Budgeted amount in milliunits format
	Budgeted          int64              `json:"budgeted"`
	CategoryGroupId   openapi_types.UUID `json:"category_group_id"`
	CategoryGroupName *string            `json:"category_group_name,omitempty"`

	// Deleted Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// GoalCadence The goal cadence. Value in range 0-14. There are two subsets of these values which behave differently. For values 0, 1, 2, and 13, the goal's due date repeats every goal_cadence * goal_cadence_frequency, where 0 = None, 1 = Monthly, 2 = Weekly, and 13 = Yearly. For example, goal_cadence 1 with goal_cadence_frequency 2 means the goal is due every other month. For values 3-12 and 14, goal_cadence_frequency is ignored and the goal's due date repeats every goal_cadence, where 3 = Every 2 Months, 4 = Every 3 Months, ..., 12 = Every 11 Months, and 14 = Every 2 Years.
	GoalCadence *int32 `json:"goal_cadence"`

	// GoalCadenceFrequency The goal cadence frequency. When goal_cadence is 0, 1, 2, or 13, a goal's due date repeats every goal_cadence * goal_cadence_frequency. For example, goal_cadence 1 with goal_cadence_frequency 2 means the goal is due every other month.  When goal_cadence is 3-12 or 14, goal_cadence_frequency is ignored.
	GoalCadenceFrequency *int32 `json:"goal_cadence_frequency"`

	// GoalCreationMonth The month a goal was created
	GoalCreationMonth *openapi_types.Date `json:"goal_creation_month"`

	// GoalDay A day offset modifier for the goal's due date. When goal_cadence is 2 (Weekly), this value specifies which day of the week the goal is due (0 = Sunday, 6 = Saturday). Otherwise, this value specifies which day of the month the goal is due (1 = 1st, 31 = 31st, null = Last day of Month).
	GoalDay *int32 `json:"goal_day"`

	// GoalMonthsToBudget The number of months, including the current month, left in the current goal period.
	GoalMonthsToBudget *int32 `json:"goal_months_to_budget"`

	// GoalNeedsWholeAmount Indicates the monthly rollover behavior for "NEED"-type goals. When "true", the goal will always ask for the target amount in the new month ("Set Aside"). When "false", previous month category funding is used ("Refill"). For other goal types, this field will be null.
	GoalNeedsWholeAmount *bool `json:"goal_needs_whole_amount"`

	// GoalOverallFunded The total amount funded towards the goal within the current goal period.
	GoalOverallFunded *int64 `json:"goal_overall_funded"`

	// GoalOverallLeft The amount of funding still needed to complete the goal within the current goal period.
	GoalOverallLeft *int64 `json:"goal_overall_left"`

	// GoalPercentageComplete The percentage completion of the goal
	GoalPercentageComplete *int32 `json:"goal_percentage_complete"`

	// GoalSnoozedAt The date/time the goal was snoozed.  If the goal is not snoozed, this will be null.
	GoalSnoozedAt *time.Time `json:"goal_snoozed_at"`

	// GoalTarget The goal target amount in milliunits
	GoalTarget *int64 `json:"goal_target"`

	// GoalTargetMonth The original target month for the goal to be completed.  Only some goal types specify this date.
	GoalTargetMonth *openapi_types.Date `json:"goal_target_month"`

	// GoalType The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
	GoalType *CategoryGoalType `json:"goal_type"`

	// GoalUnderFunded The amount of funding still needed in the current month to stay on track towards completing the goal within the current goal period. This amount will generally correspond to the 'Underfunded' amount in the web and mobile clients except when viewing a category with a Needed for Spending Goal in a future month.  The web and mobile clients will ignore any funding from a prior goal period when viewing category with a Needed for Spending Goal in a future month.
	GoalUnderFunded *int64 `json:"goal_under_funded"`

	// Hidden Whether or not the category is hidden
	Hidden bool               `json:"hidden"`
	Id     openapi_types.UUID `json:"id"`
	Name   string             `json:"name"`
	Note   *string            `json:"note"`

	// OriginalCategoryGroupId DEPRECATED: No longer used.  Value will always be null.
	OriginalCategoryGroupId *openapi_types.UUID `json:"original_category_group_id"`
}

// CategoryGoalType The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
type CategoryGoalType string

// CategoryGroup defines model for CategoryGroup.
type CategoryGroup struct {
	// Deleted Whether or not the category group has been deleted.  Deleted category groups will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// Hidden Whether or not the category group is hidden
	Hidden bool               `json:"hidden"`
	Id     openapi_types.UUID `json:"id"`
	Name   string             `json:"name"`
}

// CurrencyFormat The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
type CurrencyFormat struct {
	CurrencySymbol   string `json:"currency_symbol"`
	DecimalDigits    int32  `json:"decimal_digits"`
	DecimalSeparator string `json:"decimal_separator"`
	DisplaySymbol    bool   `json:"display_symbol"`
	ExampleFormat    string `json:"example_format"`
	GroupSeparator   string `json:"group_separator"`
	IsoCode          string `json:"iso_code"`
	SymbolFirst      bool   `json:"symbol_first"`
}

// DateFormat The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
type DateFormat struct {
	Format string `json:"format"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Detail string `json:"detail"`
	Id     string `json:"id"`
	Name   string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// LoanAccountPeriodicValue defines model for LoanAccountPeriodicValue.
type LoanAccountPeriodicValue map[string]int64

// MonthDetail defines model for MonthDetail.
type MonthDetail struct {
	// Activity The total amount of transactions in the month, excluding those categorized to 'Inflow: Ready to Assign'
	Activity int64 `json:"activity"`

	// AgeOfMoney The Age of Money as of the month
	AgeOfMoney *int32 `json:"age_of_money"`

	// Budgeted The total amount budgeted in the month
	Budgeted int64 `json:"budgeted"`

	// Categories The budget month categories.  Amounts (budgeted, activity, balance, etc.) are specific to the {month} parameter specified.
	Categories []Category `json:"categories"`

	// Deleted Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// Income The total amount of transactions categorized to 'Inflow: Ready to Assign' in the month
	Income int64              `json:"income"`
	Month  openapi_types.Date `json:"month"`
	Note   *string            `json:"note"`

	// ToBeBudgeted The available amount for 'Ready to Assign'
	ToBeBudgeted int64 `json:"to_be_budgeted"`
}

// MonthSummary defines model for MonthSummary.
type MonthSummary struct {
	// Activity The total amount of transactions in the month, excluding those categorized to 'Inflow: Ready to Assign'
	Activity int64 `json:"activity"`

	// AgeOfMoney The Age of Money as of the month
	AgeOfMoney *int32 `json:"age_of_money"`

	// Budgeted The total amount budgeted in the month
	Budgeted int64 `json:"budgeted"`

	// Deleted Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// Income The total amount of transactions categorized to 'Inflow: Ready to Assign' in the month
	Income int64              `json:"income"`
	Month  openapi_types.Date `json:"month"`
	Note   *string            `json:"note"`

	// ToBeBudgeted The available amount for 'Ready to Assign'
	ToBeBudgeted int64 `json:"to_be_budgeted"`
}

// Payee defines model for Payee.
type Payee struct {
	// Deleted Whether or not the payee has been deleted.  Deleted payees will only be included in delta requests.
	Deleted bool               `json:"deleted"`
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`

	// TransferAccountId If a transfer payee, the `account_id` to which this payee transfers to
	TransferAccountId *string `json:"transfer_account_id"`
}

// PayeeLocation defines model for PayeeLocation.
type PayeeLocation struct {
	// Deleted Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
	Deleted   bool               `json:"deleted"`
	Id        openapi_types.UUID `json:"id"`
	Latitude  string             `json:"latitude"`
	Longitude string             `json:"longitude"`
	PayeeId   openapi_types.UUID `json:"payee_id"`
}

// ScheduledSubTransaction defines model for ScheduledSubTransaction.
type ScheduledSubTransaction struct {
	// Amount The scheduled subtransaction amount in milliunits format
	Amount       int64               `json:"amount"`
	CategoryId   *openapi_types.UUID `json:"category_id"`
	CategoryName *string             `json:"category_name"`

	// Deleted Whether or not the scheduled subtransaction has been deleted. Deleted scheduled subtransactions will only be included in delta requests.
	Deleted                bool                `json:"deleted"`
	Id                     openapi_types.UUID  `json:"id"`
	Memo                   *string             `json:"memo"`
	PayeeId                *openapi_types.UUID `json:"payee_id"`
	PayeeName              *string             `json:"payee_name"`
	ScheduledTransactionId openapi_types.UUID  `json:"scheduled_transaction_id"`

	// TransferAccountId If a transfer, the account_id which the scheduled subtransaction transfers to
	TransferAccountId *openapi_types.UUID `json:"transfer_account_id"`
}

// ScheduledTransactionSummary defines model for ScheduledTransactionSummary.
type ScheduledTransactionSummary struct {
	AccountId openapi_types.UUID `json:"account_id"`

	// Amount The scheduled transaction amount in milliunits format
	Amount     int64               `json:"amount"`
	CategoryId *openapi_types.UUID `json:"category_id"`

	// DateFirst The first date for which the Scheduled Transaction was scheduled.
	DateFirst openapi_types.Date `json:"date_first"`

	// DateNext The next date for which the Scheduled Transaction is scheduled.
	DateNext openapi_types.Date `json:"date_next"`

	// Deleted Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// FlagColor The transaction flag
	FlagColor *TransactionFlagColor `json:"flag_color"`

	// FlagName The customized name of a transaction flag
	FlagName  *TransactionFlagName                 `json:"flag_name"`
	Frequency ScheduledTransactionSummaryFrequency `json:"frequency"`
	Id        openapi_types.UUID                   `json:"id"`
	Memo      *string                              `json:"memo"`
	PayeeId   *openapi_types.UUID                  `json:"payee_id"`

	// TransferAccountId If a transfer, the account_id which the scheduled transaction transfers to
	TransferAccountId *openapi_types.UUID `json:"transfer_account_id"`
}

// ScheduledTransactionSummaryFrequency defines model for ScheduledTransactionSummary.Frequency.
type ScheduledTransactionSummaryFrequency string

// SubTransaction defines model for SubTransaction.
type SubTransaction struct {
	// Amount The subtransaction amount in milliunits format
	Amount       int64               `json:"amount"`
	CategoryId   *openapi_types.UUID `json:"category_id"`
	CategoryName *string             `json:"category_name"`

	// Deleted Whether or not the subtransaction has been deleted.  Deleted subtransactions will only be included in delta requests.
	Deleted       bool                `json:"deleted"`
	Id            string              `json:"id"`
	Memo          *string             `json:"memo"`
	PayeeId       *openapi_types.UUID `json:"payee_id"`
	PayeeName     *string             `json:"payee_name"`
	TransactionId string              `json:"transaction_id"`

	// TransferAccountId If a transfer, the account_id which the subtransaction transfers to
	TransferAccountId *openapi_types.UUID `json:"transfer_account_id"`

	// TransferTransactionId If a transfer, the id of transaction on the other side of the transfer
	TransferTransactionId *string `json:"transfer_transaction_id"`
}

// TransactionClearedStatus The cleared status of the transaction
type TransactionClearedStatus string

// TransactionFlagColor The transaction flag
type TransactionFlagColor string

// TransactionFlagName The customized name of a transaction flag
type TransactionFlagName = string

// TransactionSummary defines model for TransactionSummary.
type TransactionSummary struct {
	AccountId openapi_types.UUID `json:"account_id"`

	// Amount The transaction amount in milliunits format
	Amount int64 `json:"amount"`

	// Approved Whether or not the transaction is approved
	Approved   bool                `json:"approved"`
	CategoryId *openapi_types.UUID `json:"category_id"`

	// Cleared The cleared status of the transaction
	Cleared TransactionClearedStatus `json:"cleared"`

	// Date The transaction date in ISO format (e.g. 2016-12-01)
	Date openapi_types.Date `json:"date"`

	// DebtTransactionType If the transaction is a debt/loan account transaction, the type of transaction
	DebtTransactionType *TransactionSummaryDebtTransactionType `json:"debt_transaction_type"`

	// Deleted Whether or not the transaction has been deleted.  Deleted transactions will only be included in delta requests.
	Deleted bool `json:"deleted"`

	// FlagColor The transaction flag
	FlagColor *TransactionFlagColor `json:"flag_color"`

	// FlagName The customized name of a transaction flag
	FlagName *TransactionFlagName `json:"flag_name"`
	Id       string               `json:"id"`

	// ImportId If the transaction was imported, this field is a unique (by account) import identifier.  If this transaction was imported through File Based Import or Direct Import and not through the API, the import_id will have the format: 'YNAB:[milliunit_amount]:[iso_date]:[occurrence]'.  For example, a transaction dated 2015-12-30 in the amount of -$294.23 USD would have an import_id of 'YNAB:-294230:2015-12-30:1'.  If a second transaction on the same account was imported and had the same date and same amount, its import_id would be 'YNAB:-294230:2015-12-30:2'.
	ImportId *string `json:"import_id"`

	// ImportPayeeName If the transaction was imported, the payee name that was used when importing and before applying any payee rename rules
	ImportPayeeName *string `json:"import_payee_name"`

	// ImportPayeeNameOriginal If the transaction was imported, the original payee name as it appeared on the statement
	ImportPayeeNameOriginal *string `json:"import_payee_name_original"`

	// MatchedTransactionId If transaction is matched, the id of the matched transaction
	MatchedTransactionId *string             `json:"matched_transaction_id"`
	Memo                 *string             `json:"memo"`
	PayeeId              *openapi_types.UUID `json:"payee_id"`

	// TransferAccountId If a transfer transaction, the account to which it transfers
	TransferAccountId *openapi_types.UUID `json:"transfer_account_id"`

	// TransferTransactionId If a transfer transaction, the id of transaction on the other side of the transfer
	TransferTransactionId *string `json:"transfer_transaction_id"`
}

// TransactionSummaryDebtTransactionType If the transaction is a debt/loan account transaction, the type of transaction
type TransactionSummaryDebtTransactionType string

// User defines model for User.
type User struct {
	Id openapi_types.UUID `json:"id"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// GetBudgetsParams defines parameters for GetBudgets.
type GetBudgetsParams struct {
	// IncludeAccounts Whether to include the list of budget accounts
	IncludeAccounts *bool `form:"include_accounts,omitempty" json:"include_accounts,omitempty"`
}

// GetBudgetByIdParams defines parameters for GetBudgetById.
type GetBudgetByIdParams struct {
	// LastKnowledgeOfServer The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
	LastKnowledgeOfServer *int64 `form:"last_knowledge_of_server,omitempty" json:"last_knowledge_of_server,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List budgets
	// (GET /budgets)
	GetBudgets(w http.ResponseWriter, r *http.Request, params GetBudgetsParams)
	// Single budget
	// (GET /budgets/{budget_id})
	GetBudgetById(w http.ResponseWriter, r *http.Request, budgetId string, params GetBudgetByIdParams)
	// User info
	// (GET /user)
	GetUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBudgets operation middleware
func (siw *ServerInterfaceWrapper) GetBudgets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBudgetsParams

	// ------------- Optional query parameter "include_accounts" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_accounts", r.URL.Query(), &params.IncludeAccounts)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_accounts", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBudgets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBudgetById operation middleware
func (siw *ServerInterfaceWrapper) GetBudgetById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "budget_id" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "budget_id", r.PathValue("budget_id"), &budgetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "budget_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBudgetByIdParams

	// ------------- Optional query parameter "last_knowledge_of_server" -------------

	err = runtime.BindQueryParameter("form", true, false, "last_knowledge_of_server", r.URL.Query(), &params.LastKnowledgeOfServer)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last_knowledge_of_server", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBudgetById(w, r, budgetId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/budgets", wrapper.GetBudgets)
	m.HandleFunc("GET "+options.BaseURL+"/budgets/{budget_id}", wrapper.GetBudgetById)
	m.HandleFunc("GET "+options.BaseURL+"/user", wrapper.GetUser)

	return m
}
